# set velocity control
use_vel: true

takeoff_alt: 3.0

# set velocity control PID gain
pid:
  kp: 1.0

# distance between drones
spacing: 5.0

# setpoint control params
setpoint:
  kp_seek: 1.0
  kp_sp: 1.0
  range_sp: 2.0
  max_speed: 3.0
  separate: true