# set velocity control
use_velocity_controller: true

takeoff_alt: 3.0

# set velocity control PID gain
pid:
  kp: 0.8

# distance between drones
spacing: 3.0
radius: 8.0
distance_x: 3.0
distance_y: 3.0
scen6: false

scen_num: 57 # scenario 숫자 9
scen: '987'

# setpoint control params
local_plan:
  kp_attractive: 1.0
  kp_repulsive: 1.5
  repulsive_range: 2.5
  max_speed: 3.0
  use_repulsive_force: true