# set velocity control
use_vel: true

takeoff_alt: 3.0

# set velocity control PID gain
pid:
  kp: 0.8

# distance between drones
spacing: 3.0
distance_x: 3.0
distance_y: 3.0
scen6: false

scen_num: 57 # scenario 숫자 3
scen: '987'

# setpoint control params
setpoint:
  kp_seek: 1.0
  kp_sp: 1.5
  range_sp: 2.5
  max_speed: 3.0
  separate: true